// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    tags,
    tagModeConfigs,
    sessions,
    sessionSegments,
    activeTimerStates,
    appSettings,
  ];
  late final Shape0 tags = Shape0(
    source: i0.VersionedTable(
      entityName: 'tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 tagModeConfigs = Shape1(
    source: i0.VersionedTable(
      entityName: 'tag_mode_configs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(tag_id, mode)'],
      columns: [
        _column_0,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 sessions = Shape2(
    source: i0.VersionedTable(
      entityName: 'sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_7,
        _column_8,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 sessionSegments = Shape3(
    source: i0.VersionedTable(
      entityName: 'session_segments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(session_id, order_index)'],
      columns: [
        _column_0,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 activeTimerStates = Shape4(
    source: i0.VersionedTable(
      entityName: 'active_timer_states',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_29,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 appSettings = Shape5(
    source: i0.VersionedTable(
      entityName: 'app_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get color =>
      columnsByName['color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'color',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'#6366F1\'',
      defaultValue: const i1.CustomExpression('\'#6366F1\''),
    );
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sort_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'deleted_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tagId =>
      columnsByName['tag_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mode =>
      columnsByName['mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get focusDurationSec =>
      columnsByName['focus_duration_sec']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get shortBreakDurationSec =>
      columnsByName['short_break_duration_sec']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get longBreakDurationSec =>
      columnsByName['long_break_duration_sec']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sessionsBeforeLongBreak =>
      columnsByName['sessions_before_long_break']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get totalCycles =>
      columnsByName['total_cycles']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get autoStartBreak =>
      columnsByName['auto_start_break']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get autoStartFocus =>
      columnsByName['auto_start_focus']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get defaultDurationSec =>
      columnsByName['default_duration_sec']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reminderIntervalMin =>
      columnsByName['reminder_interval_min']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reminderEnabled =>
      columnsByName['reminder_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tag_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES tags(id)',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'mode',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'focus_duration_sec',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'short_break_duration_sec',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'long_break_duration_sec',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sessions_before_long_break',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_cycles',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'auto_start_break',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'auto_start_focus',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'default_duration_sec',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'reminder_interval_min',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'reminder_enabled',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tagId =>
      columnsByName['tag_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mode =>
      columnsByName['mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endedAt =>
      columnsByName['ended_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get timelineDate =>
      columnsByName['timeline_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get totalActiveSec =>
      columnsByName['total_active_sec']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get totalPausedSec =>
      columnsByName['total_paused_sec']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get configSnapshotJson =>
      columnsByName['config_snapshot_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get pomodoroFocusCount =>
      columnsByName['pomodoro_focus_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get pomodoroCyclesCompleted =>
      columnsByName['pomodoro_cycles_completed']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get pomodoroCyclesTarget =>
      columnsByName['pomodoro_cycles_target']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'active\'',
      defaultValue: const i1.CustomExpression('\'active\''),
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'started_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ended_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'timeline_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_active_sec',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_paused_sec',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'config_snapshot_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pomodoro_focus_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pomodoro_cycles_completed',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pomodoro_cycles_target',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get orderIndex =>
      columnsByName['order_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get plannedSec =>
      columnsByName['planned_sec']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get actualSec =>
      columnsByName['actual_sec']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get segmentPausedSec =>
      columnsByName['segment_paused_sec']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get segmentStatus =>
      columnsByName['segment_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endedAt =>
      columnsByName['ended_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'session_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES sessions(id)',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'order_index',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'planned_sec',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'actual_sec',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'segment_paused_sec',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'segment_status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'pending\'',
      defaultValue: const i1.CustomExpression('\'pending\''),
    );
i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'started_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get engineState =>
      columnsByName['engine_state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get currentSegmentId =>
      columnsByName['current_segment_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get segmentStartedAt =>
      columnsByName['segment_started_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get flexibleReminderActiveSec =>
      columnsByName['flexible_reminder_active_sec']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastPersistedAt =>
      columnsByName['last_persisted_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'engine_state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'current_segment_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES session_segments(id)',
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'segment_started_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'flexible_reminder_active_sec',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_persisted_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get alertTone =>
      columnsByName['alert_tone']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get alertToneBreakOver =>
      columnsByName['alert_tone_break_over']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get alertToneFocusFailure =>
      columnsByName['alert_tone_focus_failure']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get focusMode =>
      columnsByName['focus_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get whitelistJson =>
      columnsByName['whitelist_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get focusViolationThresholdSec =>
      columnsByName['focus_violation_threshold_sec']!
          as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get theme =>
      columnsByName['theme']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get alwaysOnDisplay =>
      columnsByName['always_on_display']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get language =>
      columnsByName['language']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get weekStartDay =>
      columnsByName['week_start_day']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get timeFormat =>
      columnsByName['time_format']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get trackFailedSessions =>
      columnsByName['track_failed_sessions']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get trackManualDuration =>
      columnsByName['track_manual_duration']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'alert_tone',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'success_arpeggio\'',
      defaultValue: const i1.CustomExpression('\'success_arpeggio\''),
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'alert_tone_break_over',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'break_coin\'',
      defaultValue: const i1.CustomExpression('\'break_coin\''),
    );
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'alert_tone_focus_failure',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'failure_wrong\'',
      defaultValue: const i1.CustomExpression('\'failure_wrong\''),
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'focus_mode',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'loose\'',
      defaultValue: const i1.CustomExpression('\'loose\''),
    );
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'whitelist_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<int> _column_47(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'focus_violation_threshold_sec',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 5',
      defaultValue: const i1.CustomExpression('5'),
    );
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'theme',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'system\'',
      defaultValue: const i1.CustomExpression('\'system\''),
    );
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'always_on_display',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'language',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'en\'',
      defaultValue: const i1.CustomExpression('\'en\''),
    );
i1.GeneratedColumn<int> _column_51(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'week_start_day',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'time_format',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'24h\'',
      defaultValue: const i1.CustomExpression('\'24h\''),
    );
i1.GeneratedColumn<int> _column_53(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'track_failed_sessions',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_54(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'track_manual_duration',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    tags,
    tagModeConfigs,
    sessions,
    sessionSegments,
    activeTimerStates,
    appSettings,
  ];
  late final Shape0 tags = Shape0(
    source: i0.VersionedTable(
      entityName: 'tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 tagModeConfigs = Shape1(
    source: i0.VersionedTable(
      entityName: 'tag_mode_configs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(tag_id, mode)'],
      columns: [
        _column_0,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 sessions = Shape2(
    source: i0.VersionedTable(
      entityName: 'sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_7,
        _column_8,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 sessionSegments = Shape3(
    source: i0.VersionedTable(
      entityName: 'session_segments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(session_id, order_index)'],
      columns: [
        _column_0,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 activeTimerStates = Shape6(
    source: i0.VersionedTable(
      entityName: 'active_timer_states',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_29,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_55,
        _column_56,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 appSettings = Shape5(
    source: i0.VersionedTable(
      entityName: 'app_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get engineState =>
      columnsByName['engine_state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get currentSegmentId =>
      columnsByName['current_segment_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get segmentStartedAt =>
      columnsByName['segment_started_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get flexibleReminderActiveSec =>
      columnsByName['flexible_reminder_active_sec']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastPersistedAt =>
      columnsByName['last_persisted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get pauseStartedAt =>
      columnsByName['pause_started_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get frozenRemainingSec =>
      columnsByName['frozen_remaining_sec']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_55(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pause_started_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_56(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'frozen_remaining_sec',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    tags,
    tagModeConfigs,
    sessions,
    sessionSegments,
    activeTimerStates,
    appSettings,
  ];
  late final Shape0 tags = Shape0(
    source: i0.VersionedTable(
      entityName: 'tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 tagModeConfigs = Shape1(
    source: i0.VersionedTable(
      entityName: 'tag_mode_configs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(tag_id, mode)'],
      columns: [
        _column_0,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 sessions = Shape2(
    source: i0.VersionedTable(
      entityName: 'sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_7,
        _column_8,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 sessionSegments = Shape3(
    source: i0.VersionedTable(
      entityName: 'session_segments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(session_id, order_index)'],
      columns: [
        _column_0,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 activeTimerStates = Shape6(
    source: i0.VersionedTable(
      entityName: 'active_timer_states',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_29,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_55,
        _column_56,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 appSettings = Shape5(
    source: i0.VersionedTable(
      entityName: 'app_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    tags,
    tagModeConfigs,
    sessions,
    sessionSegments,
    activeTimerStates,
    appSettings,
  ];
  late final Shape0 tags = Shape0(
    source: i0.VersionedTable(
      entityName: 'tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 tagModeConfigs = Shape1(
    source: i0.VersionedTable(
      entityName: 'tag_mode_configs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(tag_id, mode)'],
      columns: [
        _column_0,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 sessions = Shape2(
    source: i0.VersionedTable(
      entityName: 'sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_7,
        _column_8,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 sessionSegments = Shape3(
    source: i0.VersionedTable(
      entityName: 'session_segments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(session_id, order_index)'],
      columns: [
        _column_0,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 activeTimerStates = Shape6(
    source: i0.VersionedTable(
      entityName: 'active_timer_states',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_29,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_55,
        _column_56,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 appSettings = Shape7(
    source: i0.VersionedTable(
      entityName: 'app_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get alertTone =>
      columnsByName['alert_tone']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get alertToneBreakOver =>
      columnsByName['alert_tone_break_over']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get alertToneFocusFailure =>
      columnsByName['alert_tone_focus_failure']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get focusMode =>
      columnsByName['focus_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get whitelistJson =>
      columnsByName['whitelist_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get focusViolationThresholdSec =>
      columnsByName['focus_violation_threshold_sec']!
          as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get theme =>
      columnsByName['theme']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get alwaysOnDisplay =>
      columnsByName['always_on_display']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get language =>
      columnsByName['language']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get weekStartDay =>
      columnsByName['week_start_day']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get timeFormat =>
      columnsByName['time_format']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get trackFailedSessions =>
      columnsByName['track_failed_sessions']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    tags,
    tagModeConfigs,
    sessions,
    sessionSegments,
    activeTimerStates,
    appSettings,
  ];
  late final Shape0 tags = Shape0(
    source: i0.VersionedTable(
      entityName: 'tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 tagModeConfigs = Shape1(
    source: i0.VersionedTable(
      entityName: 'tag_mode_configs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(tag_id, mode)'],
      columns: [
        _column_0,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 sessions = Shape2(
    source: i0.VersionedTable(
      entityName: 'sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_7,
        _column_8,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 sessionSegments = Shape3(
    source: i0.VersionedTable(
      entityName: 'session_segments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(session_id, order_index)'],
      columns: [
        _column_0,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 activeTimerStates = Shape6(
    source: i0.VersionedTable(
      entityName: 'active_timer_states',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_29,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_55,
        _column_56,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 appSettings = Shape8(
    source: i0.VersionedTable(
      entityName: 'app_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_42,
        _column_43,
        _column_44,
        _column_57,
        _column_58,
        _column_59,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get alertTone =>
      columnsByName['alert_tone']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get alertToneBreakOver =>
      columnsByName['alert_tone_break_over']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get alertToneFocusFailure =>
      columnsByName['alert_tone_focus_failure']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get alertHapticEnabled =>
      columnsByName['alert_haptic_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get alertSoundMuted =>
      columnsByName['alert_sound_muted']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get alertFlashEnabled =>
      columnsByName['alert_flash_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get focusMode =>
      columnsByName['focus_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get whitelistJson =>
      columnsByName['whitelist_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get focusViolationThresholdSec =>
      columnsByName['focus_violation_threshold_sec']!
          as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get theme =>
      columnsByName['theme']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get alwaysOnDisplay =>
      columnsByName['always_on_display']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get language =>
      columnsByName['language']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get weekStartDay =>
      columnsByName['week_start_day']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get timeFormat =>
      columnsByName['time_format']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get trackFailedSessions =>
      columnsByName['track_failed_sessions']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_57(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'alert_haptic_enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_58(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'alert_sound_muted',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_59(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'alert_flash_enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
    from5To6: from5To6,
  ),
);
